apiVersion: v1
kind: Service
metadata:
  name: yml-remote-pingme-service
  namespace: default
spec:
  type: NodePort
  selector:
      service_id: remote-ping-me-from-yml
  ports:
  - nodePort: 30081
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: yml-local-pingme-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
      service_id: local-ping-me-from-yml
  ports:
  - port: 30091
    targetPort: 8080 