version: "3.8"

services:
  pingme_remote:
    image: mongo
    container_name: pmr
    restart: always
    ports:
      - "8090:8090"
  ping_local:
    depends_on:
      - "pingme_remote"
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: pml
    restart: always
    ports:
      - "8080:8090"
    environment:
      PINGME_ENDPOINT: "pmr:8090"

networks:
  default:
    name: pingme-net
    external: false
